import { registerUiMessages, type UiMessageValue } from '@/lib/uiMessages'

export const homeZhMessages = {
  'home.screenshot.expand': '查看原图',
  'home.lattice.source': "《西游记》世界模型示例",
  'home.lattice.close': "收起设定",
  'home.lattice.relationship': "师徒",
  'home.injection.layers': "设定层次",
  'home.injection.source': "《西游记》第二十七回 · 节选",
  'home.injection.surfaceNote': "续写时，会带入这一层设定。",

  'home.hero.title': '先理解世界，再写出好故事',
  'home.hero.description': "从正文构建世界模型，让续写承接每一处设定。",
  'home.hero.cta': '开始写作',
  'home.hero.download': '下载桌面版',
  'home.injection.title': "让世界设定，落在此刻的故事里",
  'home.injection.description': "这一章写到谁，就带上谁的设定。点选正文中的名字，看看续写会读到什么。",
  'home.injection.footnote': (params) =>
    `续写时只注入本章涉及的 ${params.entities} 个实体、${params.relations} 条关系、${params.systems} 条约束`,
  'home.injection.layer.surface': '表面',
  'home.injection.layer.truth': '真相',
  'home.injection.relations': "本章实体与关系",
  'home.injection.truthNote': "作者保留的真相，不作为设定注入续写。",
  'home.surfaces.title': "一部小说，三个视角",
  'home.surfaces.description': "写正文、理设定、查线索，都围绕同一个世界模型。",
  'home.lattice.stat.entities': '实体',
  'home.lattice.stat.relations': '关系',
  'home.lattice.stat.systems': '体系',
  'home.lattice.label.surface': '表面',
  'home.lattice.label.truth': '真相',
  'home.lattice.type.character': '人物',
  'home.lattice.type.location': '地点',
  'home.lattice.type.item': '物品',
  'home.lattice.type.faction': '势力',
  'home.cta.facts': "桌面版支持自备 API 密钥与 OpenAI 兼容接口，作品保存在本机。AGPLv3 开源。",
  'home.download.windows': 'Windows x64',
  'home.download.macos': 'macOS Apple Silicon',
  'home.feature.studio.eyebrow': "写作台",
  'home.feature.studio.title': "把注意力留给故事",
  'home.feature.studio.description': "章节、正文与续写并排展开。读到哪里，就从哪里接着写。",
  'home.feature.studio.alt': 'NovWr 写作台界面',
  'home.feature.atlas.eyebrow': "世界地图",
  'home.feature.atlas.title': "看清人物，也看清关系",
  'home.feature.atlas.description': "人物档案、势力关系与世界体系，在同一处查阅、编辑和审核。",
  'home.feature.atlas.alt': 'NovWr 世界地图界面',
  'home.feature.copilot.eyebrow': "AI 助手",
  'home.feature.copilot.title': "每条线索，都有来处",
  'home.feature.copilot.description': "直接向助手提问，沿引用回到原文章节，核实细节后继续写。",
  'home.feature.copilot.alt': 'NovWr AI 助手界面',
  'home.workflow.title': "从正文，到下一章",
  'home.workflow.description': "导入、补全、审核、查阅，然后续写。",
  'home.workflow.currentStep': '当前步骤',
  // ── Act 1: Import ──
  'home.narrative.act1.eyebrow': "导入",
  'home.narrative.act1.title': "把故事交进来，人物关系浮出来",
  'home.narrative.act1.description': "导入已有正文，逐章提取人物、地点与关系，整理成可查、可改的世界模型。",
  // ── Act 2: Settings / Build ──
  'home.narrative.act2.eyebrow': "补全",
  'home.narrative.act2.title': "补上正文之外的世界规则",
  'home.narrative.act2.description': "粘贴力量分级、阵营法则等设定，生成世界体系，补全故事背后的规则。",
  // ── Act 3: Governance / Review ──
  'home.narrative.act3.eyebrow': "审核",
  'home.narrative.act3.title': "AI 起草，由你定稿",
  'home.narrative.act3.description': "实体、关系、体系分开审核。逐条确认、修改或拒绝，让设定按你的意思生效。",
  // ── Act 4: Copilot ──
  'home.narrative.act4.eyebrow': "查阅",
  'home.narrative.act4.title': "循着出处，找回故事里的细节",
  'home.narrative.act4.description': "向助手提问，从回答中的引用回到原文，核实角色经历与情节线索。",
  // ── Act 5: Continuation ──
  'home.narrative.act5.eyebrow': "续写",
  'home.narrative.act5.title': "带着已确认的设定，写下一章",
  'home.narrative.act5.description': "续写带入本章相关的角色、关系与规则。比较候选版本，留下合适的一段，再接着改。",
  // ── Closing CTA ──
  'home.cta.title': "你的世界，还有下一章",
  'home.cta.description': "带上已经写下的故事，从这里继续。",
  'home.cta.button': "开始写作",
  // ── Stage window labels & captions ──
  'home.stage.window.library': 'NovWr Library',
  'home.stage.window.studio': 'NovWr Studio',
  'home.stage.window.atlas': 'NovWr Atlas',
  'home.stage.window.copilot': 'NovWr Copilot',
  'home.stage.caption.import': 'Library — 导入与章节管理',
  'home.stage.caption.settings': 'Atlas — 从设定文本生成世界体系',
  'home.stage.caption.governance': 'Atlas — 草稿审核与定稿',
  'home.stage.caption.copilot': 'Copilot — AI 研究助手',
  'home.stage.caption.continuation': 'Studio — 回到续写',
} as const satisfies Record<string, UiMessageValue>

export const homeEnMessages = {
  'home.screenshot.expand': 'View full image',
  'home.lattice.source': "Journey to the West · world model",
  'home.lattice.close': "Close setting",
  'home.lattice.relationship': "Mentor and disciple",
  'home.injection.layers': "Setting layers",
  'home.injection.source': "Journey to the West · Chapter 27 excerpt",
  'home.injection.surfaceNote': "This setting accompanies the continuation.",

  'home.hero.title': 'Understand the world first.\nWrite better stories.',
  'home.hero.description': "Build a world model from your manuscript. Carry its characters, relationships, and rules into the next chapter.",
  'home.hero.cta': 'Start writing',
  'home.hero.download': 'Download desktop',
  'home.injection.title': "Bring your world into this chapter",
  'home.injection.description': "Select a name in the passage to see the setting that accompanies this chapter.",
  'home.injection.footnote': (params) =>
    `This chapter injects ${params.entities} entities, ${params.relations} relationships, ${params.systems} ${params.systems === 1 ? 'constraint' : 'constraints'}`,
  'home.injection.layer.surface': 'Surface',
  'home.injection.layer.truth': 'Truth',
  'home.injection.relations': "Characters and relationships in this chapter",
  'home.injection.truthNote': "Private author notes are excluded from the settings sent to continuation.",
  'home.surfaces.title': "One novel, three perspectives",
  'home.surfaces.description': "Write, organize your world, and look up details around one shared world model.",
  'home.lattice.stat.entities': 'entities',
  'home.lattice.stat.relations': 'relationships',
  'home.lattice.stat.systems': 'system',
  'home.lattice.label.surface': 'Surface',
  'home.lattice.label.truth': 'Truth',
  'home.lattice.type.character': 'Character',
  'home.lattice.type.location': 'Location',
  'home.lattice.type.item': 'Item',
  'home.lattice.type.faction': 'Faction',
  'home.cta.facts': "The desktop app supports your own API key and OpenAI-compatible services, with manuscripts stored locally. Open source under AGPLv3.",
  'home.download.windows': 'Windows x64',
  'home.download.macos': 'macOS Apple Silicon',
  'home.narrative.act1.eyebrow': "Import",
  'home.narrative.act1.title': "Bring in the story. Reveal its connections.",
  'home.narrative.act1.description': "Import your manuscript to extract characters, places, and relationships chapter by chapter.",
  'home.narrative.act2.eyebrow': "Build",
  'home.narrative.act2.title': "Give the world its unwritten rules",
  'home.narrative.act2.description': "Turn your notes on power levels, factions, and world rules into structured systems.",
  'home.narrative.act3.eyebrow': "Review",
  'home.narrative.act3.title': "AI drafts. You decide what becomes canon.",
  'home.narrative.act3.description': "Review entities, relationships, and systems. Approve, edit, or reject each draft before it becomes canon.",
  'home.narrative.act4.eyebrow': "Look up",
  'home.narrative.act4.title': "Find the detail. Follow the source.",
  'home.narrative.act4.description': "Ask the assistant about a character or plot detail, then follow its citations back to your manuscript.",
  'home.narrative.act5.eyebrow': "Continue",
  'home.narrative.act5.title': "Continue with the world you have defined",
  'home.narrative.act5.description': "Continue with relevant characters, relationships, and rules. Compare candidates, choose a passage, and make it yours.",
  'home.cta.title': "Your world has another chapter",
  'home.cta.description': "Bring the story you have written. Take it further.",
  'home.cta.button': "Start writing",
  'home.feature.studio.eyebrow': "Studio",
  'home.feature.studio.title': "Stay with your story",
  'home.feature.studio.description': "Keep chapters, prose, and continuation side by side. Pick up the story right where you are reading.",
  'home.feature.studio.alt': 'NovWr Studio workspace',
  'home.feature.atlas.eyebrow': "Atlas",
  'home.feature.atlas.title': "See the cast and their connections",
  'home.feature.atlas.description': "Browse, edit, and review character profiles, faction relationships, and world systems together.",
  'home.feature.atlas.alt': 'NovWr Atlas workspace',
  'home.feature.copilot.eyebrow': "Copilot",
  'home.feature.copilot.title': "Follow a detail back to its source",
  'home.feature.copilot.description': "Ask the assistant, follow its citations to the manuscript, and return to writing.",
  'home.feature.copilot.alt': 'NovWr Copilot workspace',
  'home.workflow.title': "From manuscript to the next chapter",
  'home.workflow.description': "Import, build, review, look up, then continue.",
  'home.workflow.currentStep': 'Current step',
  'home.stage.window.library': 'NovWr Library',
  'home.stage.window.studio': 'NovWr Studio',
  'home.stage.window.atlas': 'NovWr Atlas',
  'home.stage.window.copilot': 'NovWr Copilot',
  'home.stage.caption.import': 'Library — import and chapter management',
  'home.stage.caption.settings': 'Atlas — generate world systems from setting text',
  'home.stage.caption.governance': 'Atlas — draft review and sign-off',
  'home.stage.caption.copilot': 'Copilot — research assistant',
  'home.stage.caption.continuation': 'Studio — back to continuation',
} as const satisfies Partial<Record<keyof typeof homeZhMessages, UiMessageValue>>

export const homeUiMessages = {
  zh: homeZhMessages,
  en: homeEnMessages,
} as const

registerUiMessages(homeUiMessages)
